# Generated by Django 5.1.4 on 2025-10-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BNIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('P', models.IntegerField(default=0)),
                ('A', models.IntegerField(default=0)),
                ('L', models.IntegerField(default=0)),
                ('M', models.IntegerField(default=0)),
                ('S', models.IntegerField(default=0)),
                ('RGI', models.IntegerField(default=0)),
                ('RGO', models.IntegerField(default=0)),
                ('RRI', models.IntegerField(default=0)),
                ('RRO', models.IntegerField(default=0)),
                ('V', models.IntegerField(default=0)),
                ('one_to_one', models.IntegerField(default=0)),
                ('TYFCB', models.BigIntegerField(default=0)),
                ('CEU', models.IntegerField(default=0)),
                ('T', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='reports_bni_last_na_b2ccbc_idx'), models.Index(fields=['start_date', 'end_date'], name='reports_bni_start_d_269b76_idx')],
            },
        ),
    ]
