# Generated by Django 5.1.4 on 2025-10-28 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberMonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P', models.IntegerField(default=0)),
                ('A', models.IntegerField(default=0)),
                ('L', models.IntegerField(default=0)),
                ('M', models.IntegerField(default=0)),
                ('S', models.IntegerField(default=0)),
                ('RGI', models.IntegerField(default=0)),
                ('RGO', models.IntegerField(default=0)),
                ('RRI', models.IntegerField(default=0)),
                ('RRO', models.IntegerField(default=0)),
                ('V', models.IntegerField(default=0)),
                ('one_to_one', models.IntegerField(default=0)),
                ('TYFCB', models.BigIntegerField(default=0)),
                ('CEU', models.IntegerField(default=0)),
                ('T', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('color', models.CharField(default='GREY', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BNIReport',
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['last_name', 'first_name'], name='reports_mem_last_na_557138_idx'),
        ),
        migrations.AddField(
            model_name='membermonthlyreport',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='reports.member'),
        ),
        migrations.AddIndex(
            model_name='reportingperiod',
            index=models.Index(fields=['year', 'month'], name='reports_rep_year_222747_idx'),
        ),
        migrations.AddIndex(
            model_name='reportingperiod',
            index=models.Index(fields=['start_date', 'end_date'], name='reports_rep_start_d_2f0817_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportingperiod',
            unique_together={('year', 'month')},
        ),
        migrations.AddField(
            model_name='membermonthlyreport',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_reports', to='reports.reportingperiod'),
        ),
        migrations.AddIndex(
            model_name='membermonthlyreport',
            index=models.Index(fields=['member', 'period'], name='reports_mem_member__d2125f_idx'),
        ),
        migrations.AddIndex(
            model_name='membermonthlyreport',
            index=models.Index(fields=['color'], name='reports_mem_color_9a1593_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membermonthlyreport',
            unique_together={('member', 'period')},
        ),
    ]
