# Generated by Django 5.1.4 on 2025-10-29 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_member_membermonthlyreport_reportingperiod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='membermonthlyreport',
            name='reports_mem_member__d2125f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='membermonthlyreport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='membermonthlyreport',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.uploadbatch'),
        ),
        migrations.AlterUniqueTogether(
            name='membermonthlyreport',
            unique_together={('member', 'period', 'batch')},
        ),
        migrations.AddIndex(
            model_name='membermonthlyreport',
            index=models.Index(fields=['member', 'period', 'batch'], name='reports_mem_member__b42d6b_idx'),
        ),
    ]
